### ISSUE TITLE
`zfs` command to recursively mount a specific dataset

### ISSUE THREAD

**Issue by QORTEC** [Jip-Hop/truenas-scale-trigger-autobackup#1]
There is a error in the README.md file: (Introduced in commit f666a5f724b9c5c2bef368037dbf50e55629d1fb)

[It currently reads](https://github.com/Jip-Hop/udev-trigger-zfs-autobackup/blob/main/README.md)
> There's currently `zfs` command to recursively mount a specific dataset.

[It used to say:](https://github.com/Jip-Hop/udev-trigger-zfs-autobackup/blob/4a19b0bf7079023ff47db235f69fe818ff94df89/README.md)
> There's currently no way to recursively mount a specific dataset.

There's currently **NO** `zfs` command to recursively mount a specific dataset.

**Comment by Jip-Hop** [comment]
Thanks for reporting. Good detective work!

I hope you didn't come across this repo hoping to find a zfs command to recursively mount a specific dataset 😆

**Comment by QORTEC** [comment]
I came across your repo on the [OpenZFS Issue #2901](openzfs/zfs/issues/2901). 
When I saw your sentence with the hyper link, I though "Did I miss something?" but it ended linking back to the same issue.
I though it best to mention/correct the minor issue before someone who doesn't know sees...
