### ISSUE TITLE
Persistence between TrueNAS upgrades

### ISSUE THREAD

**Issue by jseadragon** [Jip-Hop/truenas-scale-trigger-autobackup#2]
Hi there! Nice work. 

In the past I had thought about building something similar but my hesitation was that I would have to reconfigure most of this when I upgraded TrueNAS versions. Have you encountered this? It's completely possible I missed something when doing my original research.

**Comment by Jip-Hop** [comment]
Hi @jseadragon. I made this specifically for TrueNAS SCALE and it should survive updates if you install it [as described in the Readme](https://github.com/Jip-Hop/udev-trigger-zfs-autobackup#install-udev-trigger-zfs-autobackup). I hope it works well for you 🙂
