### ISSUE TITLE
Error creating Python env. on TreuNAS CORE 13.0

### ISSUE THREAD

**Issue by GJSchaller** [Jip-Hop/truenas-scale-trigger-autobackup#3]
When running the install script on TrueNAS CORE 13.0-U3.1, I get the following:

> root@TrueNAS[/mnt/data/scripts/zfs-autobackup]# ./trigger.sh --install
> Creating Python virtual environment...
> Error: [Errno 1] Operation not permitted: '/mnt/data/scripts/zfs-autobackup/venv/bin/Activate.ps1'
> root@TrueNAS[/mnt/data/scripts/zfs-autobackup]#

**Comment by Jip-Hop** [comment]
Could you try once with `set -euox pipefail` instead of `set -euo pipefail` on line 3 of trigger.sh for a bit more logging.

Have any files or directories been created? If so, can you run `ls -la` inside the `venv` folder? Also please run `ls -la` inside the folder where you put `trigger.sh` and post the output.

Looks like it somehow doesn't have write permissions...

**Comment by GJSchaller** [comment]
ls -la from the dir where trigger.sh is:

> total 134
> drwxrwx---+  3 root  wheel    10 Jan  4 14:54 .
> drwxrwx--x+ 13 root  wheel    15 Jan  4 13:38 ..
> -rwxrwx---+  1 root  wheel  4062 Jan  4 13:38 backup.sh
> -rwxrwx---+  1 root  wheel  1315 Jan  4 13:42 config
> -rwxrwx---+  1 root  wheel   700 Jan  4 13:38 monitor.py
> -rwxrwx---+  1 root  wheel  7796 Jan  4 13:38 README.md
> -rwxrwx---+  1 root  wheel    36 Jan  4 13:38 requirements.txt
> -rwxrwx---+  1 root  wheel  2697 Jan  4 13:38 trigger.sh
> drwxrwx---+  5 root  wheel     7 Jan  4 13:39 venv

ls -la from venv dir:

> total 30
> drwxrwx---+ 5 root  wheel   8 Jan  4 14:56 .
> drwxrwx---+ 3 root  wheel  10 Jan  4 14:54 ..
> drwxrwx---+ 2 root  wheel   6 Jan  4 13:39 bin
> drwxrwx---+ 2 root  wheel   2 Jan  4 13:39 include
> drwxrwx---+ 3 root  wheel   3 Jan  4 13:39 lib
> lrwxr-xr-x  1 root  wheel   3 Jan  4 13:39 lib64 -> lib
> -rwxrwx---+ 1 root  wheel  76 Jan  4 13:47 pyvenv.cfg

Will modify trigger.sh and report back in a moment.  Thank you for your help!  I'm logged in as root from the UI console, if that helps.

**Comment by Jip-Hop** [comment]
And maybe once an `ls -la` from `/mnt/data/scripts/zfs-autobackup/venv/bin/`?

**Comment by GJSchaller** [comment]
Logging in as a non-root user, since the UI won't let me copy & paste easily.  I'm doing this from a non-root account using Terminal on macOS.  It looks like GitHub is replacing the plus signs with bullets:

> geoffrey@TrueNAS:/mnt/data/scripts/zfs-autobackup $ ./trigger.sh --install
> ++ basename ./trigger.sh
> + SCRIPT_NAME=trigger.sh
> +++ dirname ./trigger.sh
> ++ cd .
> ++ pwd
> + SCRIPT_DIR=/mnt/data/scripts/zfs-autobackup
> + cd /mnt/data/scripts/zfs-autobackup
> ++ cat
> + STEPS='1. Manually create (encrypted) ZFS pool(s) on removable disk(s).
> 2. Manually edit config to specify the names of your backup pool(s) and the encryption passphrase.
> 3. Manually schedule trigger.sh to run at system startup. On TrueNAS SCALE: System Settings -> Advanced -> Init/Shutdown Scripts -> Add -> Description: trigger-zfs-autobackup; Type: Script; Script: /path/to/trigger.sh; When: Post Init -> Save
> 4. Manually insert backup disk whenever you want to make a backup.
> 5. Automatic backup is triggered and sends email on completion.'
> + VENV=/mnt/data/scripts/zfs-autobackup/venv
> + INSTALL=false
> + parse_params --install
> + :
> + case "${1-}" in
> + INSTALL=true
> + shift
> + :
> + case "${1-}" in
> + break
> + args=("$@")
> + return 0
> + '[' true = true ']'
> + echo 'Creating Python virtual environment...'
> Creating Python virtual environment...
> + python3 -m venv /mnt/data/scripts/zfs-autobackup/venv --without-pip
> Error: [Errno 1] Operation not permitted: '/mnt/data/scripts/zfs-autobackup/venv/bin/Activate.ps1'
> geoffrey@TrueNAS:/mnt/data/scripts/zfs-autobackup $

**Comment by GJSchaller** [comment]
> And maybe once an `ls -la` from `/mnt/data/scripts/zfs-autobackup/venv/bin/`?

geoffrey@TrueNAS:/mnt/data/scripts/zfs-autobackup/venv/bin $ ls -la
total 29
drwxrwx---+ 2 root  wheel     6 Jan  4 13:39 .
drwxrwx---+ 5 root  wheel     8 Jan  4 14:56 ..
-rwxrwx---+ 1 root  wheel  8834 Jan  4 15:06 Activate.ps1
lrwxr-xr-x  1 root  wheel     7 Jan  4 13:39 python -> python3
lrwxr-xr-x  1 root  wheel    22 Jan  4 13:39 python3 -> /usr/local/bin/python3
lrwxr-xr-x  1 root  wheel     7 Jan  4 13:39 python3.9 -> python3
geoffrey@TrueNAS:/mnt/data/scripts/zfs-autobackup/venv/bin $

**Comment by Jip-Hop** [comment]
I don't know why it's not working. It's failing at this command: `python3 -m venv /mnt/data/scripts/zfs-autobackup/venv --without-pip`. Try to see if you can get that command working with a different path (make a new folder somewhere first). Try as root user.

**Comment by GJSchaller** [comment]
OK, I made a new dir, /mnt/data/zfs-backup, and copied the files into there.  The install seems to be working now.  It's just a folder created using mkdir, and not a Dataset, if that may be the issue.  I'll work from here and see if I run into any more issues - thank you for your help!

**Comment by Jip-Hop** [comment]
Nice! Good luck :)

**Comment by GJSchaller** [comment]
I'm running into issues with the commands to create the disk - would you like me to open more issues here, or would you like to set up a discussion some time?  I know this is for CORE and not SCALE, and I'm a few hours behind you (New York area, USA) - I'm flexible on how to approach getting this working on CORE.  Thank you!

**Comment by Jip-Hop** [comment]
Please make a new issue if the documentation doesn't work for you and post which commands fail and their output, what you've tried etc. Also I recommend searching the TrueNAS forum and FreeBSD documentation on how to format a disk for ZFS. I found these: https://dalvikplanet.blogspot.com/2020/03/how-to-format-pendrive-with-zfs.html and https://forums.freebsd.org/threads/how-to-prepare-disk-for-zfs.71047/
