### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 0xabu** [Jip-Hop/truenas-scale-trigger-autobackup#5]
Hi there, and thanks for writing this tool. Would you be willing to explicitly license it under an OSS license?

I'm asking because @ghan1t forked and extended it as https://github.com/ghan1t/udev-trigger-zfs-autobackup, and I've ended up further forking that without realising that it wasn't already OSS. Hopefully we can clear that up retrospectively?

**Comment by Jip-Hop** [comment]
The [GitHub TOS already allow forking](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users).

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

But [it's not clear if this also covers modifying after forking](https://github.com/github/site-policy/issues/37#issuecomment-315911013).

I've added an MIT license to the repo. Enjoy!

**Comment by 0xabu** [comment]
Perfect, thanks!
